name: menupro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_splash_screen: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/connies.png
    - assets/images/menuproicondarktheam.png
    - assets/images/menuproiconlighttheam.png
    - assets/images/line.png
    - assets/images/united-kingdom.png
    - assets/images/united-states.png
   
  fonts:
    - family: GothomProBlack
      fonts:
        - asset: assets/fonts/GothamPro-Black.ttf
    
